name: ev_charging_app
description: A new Flutter project for EV charging.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.3.11
  mobile_scanner: ^5.0.0
  #qr_code_scanner: ^1.0.1
  dotted_border: ^2.1.0
  flutter_spinbox: ^0.13.1
  percent_indicator: ^4.2.3
  latlong2: ^0.9.1
  flutter_map: ^8.1.1
  geolocator: ^14.0.1
  provider: ^6.0.5
  image_picker: ^1.1.1
  intl: ^0.19.0
  pdf: ^3.10.8
  printing: ^5.12.0
  path_provider: ^2.1.3
  open_filex: ^4.3.2
  animated_text_kit: ^4.2.3
  video_player: ^2.9.5
  lottie: ^3.3.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.1"

# --- flutter_launcher_icons configuration ---
flutter_launcher_icons:
  android: true
  ios: false # Set to true if you also want to generate iOS icons
  image_path: "assets/AppLogo.png" # Path to your app logo
  min_sdk_android: 21 # Ensure this matches or is lower than your project's minSdkVersion in android/app/build.gradle
  adaptive_icon_background: "#FFFFFF" # A white background for adaptive icons
  adaptive_icon_foreground: "assets/AppLogo.png" # Your logo for the foreground of adaptive icons
# --- End flutter_launcher_icons configuration ---

flutter_native_splash:
  color: "#42A5F5"
  image: assets/logo.png
  android_gravity: center
  ios_content_mode: center
  web: false
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/about.png
    - assets/splash_video.mp4
    - assets/AppLogo.png # Your app logo asset